### ISSUE TITLE
What is current state of this package?

### ISSUE THREAD

**Issue by TomasVotruba** [QafooLabs/php-refactoring-browser#72]
Packages looks like abandoned, I guess because of TokenReflection - yep, I got to replace it too in [ApiGen](https://github.com/ApiGen/ApiGen/issues/817). Is that so?

I wonder, what do you instead?
How were you satisfied with this solution?

I'm into building such refactor tool so I look for experience.

**Comment by AJenbo** [comment]
There's a few forks around where most of the issue have been patched, currently I have one of both where php7 compatibility has been fixed and a nothing refactor capability added

**Comment by TomasVotruba** [comment]
Oh, that's good to know.
Could you share those links?

**Comment by AJenbo** [comment]
https://github.com/AJenbo/php-refactoring-browser

https://github.com/AJenbo/PHP-Token-Reflection

**Comment by TomasVotruba** [comment]
Thank you
