### ISSUE TITLE
Method renaming is not supported

### ISSUE THREAD

**Issue by zestllankesh** [QafooLabs/php-refactoring-browser#75]
Hi,

I am using **CodeLite** as my **PHP IDE**.
There is one limitation in that IDE and that is **Method renaming is not supported**.

I've raised that issue there. Following is the reference link:

https://github.com/eranif/codelite/issues/1725

When can we expect **Method renaming** feature in this library

**Comment by AJenbo** [comment]
Php-refactoring-browser is currently in maintenance mode only, so new features are unlikely unless they are very simple to implement or some one makes a pull request with the new feature. 
The reason for this is that multiple upstream projects have stagnated.

**Comment by zestllankesh** [comment]
Ohh.

I hope we do get this feature soon.

Thank you for your time :)

**Comment by AJenbo** [comment]
If you are able to do the code I will gladly merge it and integrated it into codelite :-)

**Comment by zestllankesh** [comment]
I'll see what I can do. :)
